import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminButton from "./AdminButton";
import CartButton from "./CartButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b border-gray-200 bg-gradient-to-r from-slate-50 to-slate-100">
          <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
            <a href="/products" className="font-semibold flex items-center gap-2">
              <span className="inline-block w-6 h-6 rounded bg-gray-800" />
              <span>Webshop</span>
            </a>
            <div className="flex items-center gap-3 ml-auto">
              <AdminButton />
              <CartButton />
            </div>
          </div>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
